<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert([
        	[
		    	'permission_title' => 'Dashboard',
		    	'permission_slug' => 'App\Http\Controllers\Admin\DashboardController@index', 
		    	'permission_description'=>'Dashboard Page',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
		    [
		    	'permission_title' => 'Index Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@index', 
		    	'permission_description'=>'List all records',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Create Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@create', 
		    	'permission_description'=>'Create Roles',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Save Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@store', 
		    	'permission_description'=>'Save roles',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Show Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@show', 
		    	'permission_description'=>'Show roles',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Edit Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@edit', 
		    	'permission_description'=>'Edit Roles',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@update', 
		    	'permission_description'=>'Update Roles',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Delete Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@destroy', 
		    	'permission_description'=>'Delete Roles',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Index Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@index', 
		    	'permission_description'=>'List all records',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Create Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@create', 
		    	'permission_description'=>'Create Permissions',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Save Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@store', 
		    	'permission_description'=>'Save Permissions',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Show Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@show', 
		    	'permission_description'=>'Show Permissions',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Edit Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@edit', 
		    	'permission_description'=>'Edit Permissions',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@update', 
		    	'permission_description'=>'Update Permissions',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Delete Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@destroy', 
		    	'permission_description'=>'Delete Permissions',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Index Permissions assignment',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionRoleController@index', 
		    	'permission_description'=>'List all records',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Create Permissions assignment',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionRoleController@create', 
		    	'permission_description'=>'Create Permissions assignment',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Save Permissions assignment',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionRoleController@store', 
		    	'permission_description'=>'Save Permissions assignment',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Show Permissions assignment',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionRoleController@show', 
		    	'permission_description'=>'Show Permissions assignment',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Edit Permissions assignment',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionRoleController@edit', 
		    	'permission_description'=>'Edit Permissions assignment',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Permissions assignment',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionRoleController@update', 
		    	'permission_description'=>'Update Permissions assignment',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Delete Permissions assignment',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionRoleController@destroy', 
		    	'permission_description'=>'Delete Permissions assignment',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Index Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@index', 
		    	'permission_description'=>'List all records',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Create Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@create', 
		    	'permission_description'=>'Create Users',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Save Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@store', 
		    	'permission_description'=>'Save Users',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Show Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@show', 
		    	'permission_description'=>'Show Users',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Edit Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@edit', 
		    	'permission_description'=>'Edit Users',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@update', 
		    	'permission_description'=>'Update Users',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Delete Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@destroy', 
		    	'permission_description'=>'Delete Users',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'View Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@index', 
		    	'permission_description'=>'View Profile',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Edit Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@edit', 
		    	'permission_description'=>'Edit Profile',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Info Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@updateInfo', 
		    	'permission_description'=>'Update Info Profile',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Security Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@updateSecurity', 
		    	'permission_description'=>'Update Security Profile',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Privacity Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@updatePrivacity', 
		    	'permission_description'=>'Update Privacity Profile',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Edit Avatar Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@editAvatar', 
		    	'permission_description'=>'Edit Avatar Profile',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Avatar Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@updateAvatar', 
		    	'permission_description'=>'Update Avatar Profile',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Confirm Email Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@confirmEmailRegistration', 
		    	'permission_description'=>'Confirm Email Profile',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
    	]);
    }
}
